version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkus_db
    ports:
      - "5432:5432"

  livros-api:
    build:
      context: ./simple-book-api
    container_name: livros-api
    depends_on:
      - postgres-db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-db:5432/quarkus_db
      - QUARKUS_DATASOURCE_USERNAME=quarkus
      - QUARKUS_DATASOURCE_PASSWORD=quarkus
    ports:
      - "8081:8080"

  usuarios-api:
    build:
      context: ./user-system
    container_name: usuarios-api
    depends_on:
      - postgres-db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-db:5432/quarkus_db
      - QUARKUS_DATASOURCE_USERNAME=quarkus
      - QUARKUS_DATASOURCE_PASSWORD=quarkus
    ports:
      - "8082:8080"
